### ISSUE TITLE
Call for contributors

### ISSUE THREAD

**Issue by Ccode-lang** [Ccode-archives/Ccode#16]
Hello I'm Ccode-lang.  This project is fully functional and (as far as I know) bug free.  If you want to contribute just tell me.  If you have any questions please ask me though this issue.

**Comment by x0tic0** [comment]
Do you have discord? Im looking to contribute

**Comment by Ccode-lang** [comment]
Hello I do not have a discord at the moment and do not plan on having one.  The closest thing that we will ever have to that is the discussions tab.  

If anyone wants to approve large changes that is the place to ask.

**Comment by x0tic0** [comment]
Im looking to make this as official as possible which require ALOT of work. Are you planning on adding a syntax checker?. The checker should be logging functions to run etc and have em execute after checking

**Comment by Ccode-lang** [comment]
Ok, I was already experimenting with a syntax checker but still need to fix a lot of problems.

**Comment by Ccode-lang** [comment]
Also I'm not sure I know what you mean by an "em."

**Comment by Ccode-lang** [comment]
This language was my first real project on GitHub.  I could not find a way to write a language in python without modules so I kind of just jumped into it.

**Comment by x0tic0** [comment]
Writing a programming language isnt a small thing. thats why. its actually writing alot of code for it to even function. at least to making a decent 'official' working programming language. Check out the repo on my Github called 'X Programming Language'. im just moving onto the syntax checker soon!

**Comment by x0tic0** [comment]
i suggest learning more about programming in general to move onto bigger stuff with this project. im willing to teach but if you dont have anything like discord, telegram or guilded then idk what to tell you

**Comment by Ccode-lang** [comment]
> Writing a programming language isnt a small thing. thats why. its actually writing alot of code for it to even function. at least to making a decent 'official' working programming language. Check out the repo on my Github called 'X Programming Language'. im just moving onto the syntax checker soon!

This project is more of a toy project than anything. The point was more for education and not to be official.

**Comment by x0tic0** [comment]
alright well then maybe I'm in the wrong place.

**Comment by 0u44** [comment]
how TF do you manage to make a language??? is it easy or hard?
also this is just a question :P

**Comment by Ccode-lang** [comment]
Hi @CPScript Depends on how you make the language.  This repo uses the easy way.  It has a transpiler witch translates the language to JS and then runs it.  I could help you make one if you want.

**Comment by 0u44** [comment]
that's cool... ill think about making one, and if i do i would like it to be called CPS (chai-Programming Script)
